name: Release Packed Application

on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Package Application
              uses: JackMcKew/pyinstaller-action-windows@6736e82336143ca2eb15d13f9b1af90dfd945042
              with:
                  path: .

            - name: Copy LICENSE.txt to dist
              run: cp LICENSE dist/windows/LICENSE.txt

            - name: Upload Artifact
              uses: actions/upload-artifact@v6
              with:
                  name: dist-windows
                  path: dist/windows

            - name: Create release
              uses: ncipollo/release-action@v1.20.0
              with:
                  artifacts: "dist/windows/*.exe"
                  tag: "${{ github.ref }}"
                  name: "${{ github.ref }}"
                  body: "${{ github.ref }}"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  draft: false
                  allowUpdates: false
                  makeLatest: true
